#!/usr/bin/env python3
"""Generate a shellf plan and an Ansible playbook that converge to the SAME state.

Why generated rather than hand-written from `examples/plans/`: those deploy real software
and would measure apt and the network, the Ansible side would have to be translated by
hand (every divergence silently biases the result), and a benchmark needs several sizes to
report a slope rather than one number. The shape below is `hosting.shellf` in miniature —
directories, config files, a mode, a key/value line, a template, a service account — with
the two expensive instructions deliberately already converged.

Parity is the whole point of the bench: every shellf instruction below has exactly one
Ansible task facing it, in the same order, with the same arguments. If the two ever
drift, run.sh catches it — it diffs the resulting filesystem state of the two
containers byte for byte and refuses to report a timing over a mismatch.

The variable part is N: the number of managed config files. The bench runs several N so
the result is a slope (cost per task), not a single number.
"""
import sys, os

N = int(sys.argv[1])
out = sys.argv[2]
# A shellf project has a fixed layout (ADR-0038): the plan lives in `plans/`, beside
# `assets/`, `defs/` and `inventories/`. The playbook sits in `ansible/` next to it.
for d in ("plans", "assets", "inventories", "ansible"):
    os.makedirs(f"{out}/{d}", exist_ok=True)

APP = "benchapp"
ROOT = "/srv/app"

# --- shellf plan -------------------------------------------------------------------
files = "\n".join(
    f'    file.write("{ROOT}/conf/svc-{i:03d}.conf", "unit={i}\\nowner=${{app_name}}\\n")'
    for i in range(N)
)
plan = f'''# Generated by gen.py — N={N}. Do not edit; edit gen.py.
app_name = "{APP}"

on target {{
  as root {{
    dir.ensure("{ROOT}")
    dir.ensure("{ROOT}/conf")
    dir.ensure("{ROOT}/data")
    dir.ensure("{ROOT}/logs")

{files}

    file.mode("{ROOT}/conf/svc-000.conf", "640")
    file.replace("{ROOT}/data/app.env", "APP_ENV", "production")
    file.template(%"app.conf.tmpl", "{ROOT}/app.conf")

    user.ensure("{APP}", "/bin/sh")
    user.group("{APP}", "adm")

    apt.install("curl")
    service.ensure("ssh", "true", "true")
  }}
}}
'''
open(f"{out}/plans/plan.shellf", "w").write(plan)

# --- Ansible playbook --------------------------------------------------------------
# One task per shellf instruction, same order. `become: true` faces `as root`.
tasks = []
for d in ["", "/conf", "/data", "/logs"]:
    tasks.append(f'''  - name: dir {ROOT}{d}
    ansible.builtin.file:
      path: {ROOT}{d}
      state: directory''')
for i in range(N):
    tasks.append(f'''  - name: conf svc-{i:03d}
    ansible.builtin.copy:
      dest: {ROOT}/conf/svc-{i:03d}.conf
      content: "unit={i}\\nowner={{{{ app_name }}}}\\n"''')
tasks.append(f'''  - name: mode on svc-000
    ansible.builtin.file:
      path: {ROOT}/conf/svc-000.conf
      mode: "0640"''')
tasks.append(f'''  - name: env line
    ansible.builtin.lineinfile:
      path: {ROOT}/data/app.env
      regexp: '^APP_ENV='
      line: 'APP_ENV=production'
      create: true''')
tasks.append(f'''  - name: app.conf template
    ansible.builtin.template:
      src: app.conf.j2
      dest: {ROOT}/app.conf''')
tasks.append(f'''  - name: user {APP}
    ansible.builtin.user:
      name: {APP}
      shell: /bin/sh''')
tasks.append(f'''  - name: group adm
    ansible.builtin.user:
      name: {APP}
      groups: adm
      append: true''')
tasks.append('''  - name: apt curl
    ansible.builtin.apt:
      name: curl
      state: present''')
tasks.append('''  - name: service ssh
    ansible.builtin.systemd_service:
      name: ssh
      state: started
      enabled: true''')

book = f'''# Generated by gen.py — N={N}. Do not edit; edit gen.py.
- hosts: target
  gather_facts: false
  become: true
  vars:
    app_name: {APP}
  tasks:
{chr(10).join(tasks)}
'''
open(f"{out}/ansible/playbook.yml", "w").write(book)
print(f"N={N}: {4 + N + 7} instructions each")
